name: Build luci-app-oc ke dirgha800

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      skip_build: ${{ steps.setvar.outputs.skip_build }}
      latest_ver: ${{ steps.setvar.outputs.latest_ver }}
      last_ver: ${{ steps.setvar.outputs.last_ver }}
      commit_msg: ${{ steps.commit-check.outputs.commit_msg }}
      latest_commit: ${{ steps.commit-check.outputs.latest_commit }}
      skip_release: ${{ steps.commit-check.outputs.skip_release }}
    steps:
      - name: Checkout repo build
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      # --- Notifikasi Commit ---
      - name: Cek Commit Terbaru
        id: commit-check
        run: |
          # Buat folder penyimpanan commit
          mkdir -p data/openclash
        
          # Ambil commit terbaru
          REPO="vernesong/OpenClash"
          BRANCH="dev"

          # Ambil commit terbaru dari branch dev
          COMMIT_JSON=$(curl -s "https://api.github.com/repos/$REPO/commits?per_page=1&sha=$BRANCH")

          LATEST_COMMIT=$(echo "$COMMIT_JSON" | grep -oP '"sha": "\K[0-9a-f]+' | head -n1)
          COMMIT_MSG=$(echo "$COMMIT_JSON" | grep -oP '"message": "\K[^"]+' | head -n1)
          COMMIT_AUTHOR=$(echo "$COMMIT_JSON" | grep -oP '"name": "\K[^"]+' | head -n1)
          # Ambil commit date dari API GitHub
          COMMIT_DATE=$(echo "$COMMIT_JSON" | jq -r '.[0].commit.committer.date')

          # Konversi ke WIB
          COMMIT_DATE_WIB=$(TZ="Asia/Jakarta" date -d "$COMMIT_DATE" '+%d-%m-%Y %H:%M:%S WIB')


          if [ -z "$LATEST_COMMIT" ]; then
            echo "âš ï¸ Gagal ambil commit dari $REPO"
            exit 1
          fi

          # Simpan commit message dan sha sebagai output
          echo "commit_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT

          if [ -f data/openclash/last_commit.sha ]; then
            OLD_COMMIT=$(cat data/openclash/last_commit.sha)
          else
            OLD_COMMIT=""
          fi

          # Ambil 7 digit pertama dari commit
          SHORT_COMMIT=${LATEST_COMMIT:0:7}

          if [ "$LATEST_COMMIT" != "$OLD_COMMIT" ]; then
            # Simpan commit terbaru
            echo "$LATEST_COMMIT" > data/openclash/last_commit.sha
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add data/openclash/last_commit.sha
            git commit -m "Update last_commit.sha ke $LATEST_COMMIT" --quiet || true
            git pull --rebase --quiet || true
            git push --quiet || true

            # Tandai agar release dijalankan
            echo "skip_release=false" >> $GITHUB_OUTPUT

            # Kirim Notifikasi Commit ke Telegram
            COMMIT_MSG=$(echo "$COMMIT_MSG" | sed 's/\&/\\&/g')
            COMMIT_URL="https://github.com/$REPO/commit/$LATEST_COMMIT"
            MSG="ğŸ†• <b>Commit baru terdeteksi</b>
          à¤•â•â•â•â•â•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•â•â•â•â•â•à¤•
          ğŸ“Œ <b>Commit:</b> <a href='$COMMIT_URL'>$SHORT_COMMIT</a>
          ğŸ“Œ <b>Author:</b> $COMMIT_AUTHOR
          ğŸ“Œ <b>Tanggal:</b> $COMMIT_DATE_WIB
          à¤•â•â•â•â•â•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•â•â•â•â•â•à¤•
          ğŸ’¬ <b>Message:</b> $COMMIT_MSG"

          else
            # Commit lama â†’ release skip
            echo "skip_release=true" >> $GITHUB_OUTPUT
          # Versi baru terdeteksi â†’ notif build dimulai
            COMMIT_MSG=$(echo "$COMMIT_MSG" | sed 's/\&/\\&/g')
            COMMIT_URL="https://github.com/$REPO/commit/$LATEST_COMMIT"
            MSG="ğŸ†• <b>openClash tidak ada Commit baru</b>
          à¤•â•â•â•â•â•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•â•â•â•â•â•à¤•
          ğŸ“Œ <b>Commit lama:</b> <a href='$COMMIT_URL'>$SHORT_COMMIT</a>
          ğŸ“Œ <b>Author:</b> $COMMIT_AUTHOR
          ğŸ“Œ <b>Tanggal:</b> $COMMIT_DATE_WIB
          à¤•â•â•â•â•â•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•â•â•â•â•â•à¤•
          ğŸ’¬ <b>Message:</b> $COMMIT_MSG"
          fi
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
              -d text="$MSG" \
              -d parse_mode="HTML" \
              -d disable_web_page_preview=true
               

      - name: Cek versi terbaru
        id: setvar
        run: |
          # Buat folder data untuk simpan info versi
          mkdir -p data/openclash

          # Path file versi
          LAST_VER_FILE="data/openclash/last_version.txt"
        
          LATEST_VER=$(curl -s https://raw.githubusercontent.com/vernesong/OpenClash/dev/luci-app-openclash/Makefile | grep -oP '(?<=PKG_VERSION:=)[0-9\.]+')
          echo "latest_ver=$LATEST_VER" >> $GITHUB_OUTPUT
          echo "Versi terbaru: $LATEST_VER"
          
           # Baca versi lama
          if [ -f "$LAST_VER_FILE" ]; then
            LAST_VER=$(cat "$LAST_VER_FILE")
          else
            LAST_VER="belum ada"
          fi
          echo "last_ver=$LAST_VER" >> $GITHUB_OUTPUT
          echo "Versi lama: $LAST_VER"

          if [ "$LAST_VER" = "$LATEST_VER" ]; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "$LATEST_VER" > "$LAST_VER_FILE"
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add "$LAST_VER_FILE"
            git commit -m "Update $LAST_VER_FILE ke $LATEST_VER" --quiet || true
            git pull --rebase --quiet || true
            git push --quiet || true
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Notif Telegram versi terbaru
        run: |
          VER="v${{ steps.setvar.outputs.latest_ver }}"
          BASE_URL="https://github.com/tes-rep/OpenClash/releases/download/$VER"
          RELEASE_URL="https://github.com/tes-rep/OpenClash/releases/tag/$VER"
          OLD_VER="v${{ steps.setvar.outputs.last_ver }}"
          

          if [[ "${{ steps.setvar.outputs.skip_build }}" == "true" ]]; then
          # Versi sama dengan terakhir
          STATUS="â„¹ï¸ <b>Tidak ada versi baru</b>"
          HEADER="Versi terakhir: <b>$VER</b>"
          MSG=$(printf "%s\n%s\n\nà¤•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•à¤•\nğŸ”— <b>Release:</b> <a href=\"%s\">Klik di sini</a>\nğŸ“¦ <b>IPK:</b> <a href=\"%s/luci-app-openclash_%s_all.ipk\">Download</a>\nğŸ“± <b>APK:</b> <a href=\"%s/luci-app-openclash-%s.apk\">Download</a>" \
            "$STATUS" \
            "$HEADER" \
            "$RELEASE_URL" \
            "$BASE_URL" "$VER" \
            "$BASE_URL" "$VER")
          else
          # Versi baru terdeteksi â†’ notif build dimulai
            MSG=$(printf "âš¡ <b>Build OpenClash dimulai...</b>\nà¤•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•à¤•\nğŸ“Œ <b>Versi baru:</b> %s\nğŸ“Œ <b>Versi lama:</b> %s\nà¤•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•à¤•\nHarap tunggu beberapa menit ğŸš€" \
              "$VER" \
              "$OLD_VER")
          fi

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="HTML" \
            -d disable_web_page_preview=true

      - name: notif build
        if: steps.commit-check.outputs.skip_release == 'false'
        run: |
          VER="v${{ steps.setvar.outputs.latest_ver }}"
          RELEASE_URL="https://github.com/tes-rep/OpenClash/releases/tag/$VER"
          BASE_URL="https://github.com/tes-rep/OpenClash/releases/download/$VER"
          OLD_VER="v${{ steps.setvar.outputs.last_ver }}"
          
          # Versi baru terdeteksi â†’ notif build dimulai
            MSG=$(printf "âš¡ <b>Build OpenClash dimulai...</b>\nà¤•â•â•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•â•â•à¤•\nğŸ“Œ <b>Versi baru:</b> %s\nğŸ“Œ <b>Versi lama:</b> %s\nà¤•â•â•â•â•â•â•â•à¤•âŠ¹âŠ±âœ«âŠ°âŠ¹à¤•â•â•â•â•â•â•â•à¤•\nHarap tunggu beberapa menit ğŸš€" \
              "$VER" \
              "$OLD_VER")

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="HTML" \
            -d disable_web_page_preview=true   

      

  build:
    needs: check-version
    if: needs.check-version.outputs.skip_build == 'false' || needs.check-version.outputs.skip_release == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ipk, mod, core, apk]
    outputs:
      build_start: ${{ steps.start.outputs.build_start }}
      build_start_human: ${{ steps.start.outputs.build_start_human }}   

    steps:
      - name: Catat waktu mulai
        id: start
        run: |
          echo "build_start=$(date +%s)" >> $GITHUB_OUTPUT
          echo "build_start_human=$(TZ=Asia/Jakarta date '+%Y-%m-%d %H:%M:%S WIB')" >> $GITHUB_OUTPUT

      
      - name: Checkout build repo
        uses: actions/checkout@v4
        
      - name: Set TARGET_DIR
        run: |
          if [ "${{ matrix.target }}" = "ipk" ]; then
            echo "TARGET_DIR=$GITHUB_WORKSPACE/SDK" >> $GITHUB_ENV
          elif [ "${{ matrix.target }}" = "mod" ]; then
            echo "TARGET_DIR=$GITHUB_WORKSPACE/MOD" >> $GITHUB_ENV
          elif [ "${{ matrix.target }}" = "core" ]; then
            echo "TARGET_DIR=$GITHUB_WORKSPACE/CORE" >> $GITHUB_ENV
          elif [ "${{ matrix.target }}" = "apk" ]; then
            echo "TARGET_DIR=$GITHUB_WORKSPACE/SNAPSDK" >> $GITHUB_ENV  
          fi  
        
      - name: cache ipk
        id: download_sdk_apk
        uses: actions/cache@v4
        with:
          path: ${{ env.TARGET_DIR }}
          key: sdk-snap-${{ matrix.target }}  


      - name: Download SDK if cache miss
        if: steps.download_sdk_apk.outputs.cache-hit != 'true'
        run: |
          set -e
          if [ "${{ matrix.target }}" == "apk" ]; then
          curl -SLk --retry 3 "https://github.com/tes-rep/tes-build/releases/download/SDK2/snap.tar.zst" -o /tmp/SNAPSDK.tar.zst
          tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp
          mv /tmp/openwrt-sdk-* "$TARGET_DIR"
          else
          curl -SLk --retry 3 "https://github.com/tes-rep/tes-build/releases/download/SDK2/15.tar.bz2" -o /tmp/SDK.tar.bz2
          tar -xjf /tmp/SDK.tar.bz2 -C /tmp
          mv /tmp/OpenWrt-SDK-* "$TARGET_DIR"
          fi


      
      - name: Clone luci-app-openclash
        run: |
          set -e
          
          cd "$TARGET_DIR/package"
          rm -rf luci-app-openclash
          git clone --depth 1 --branch dev --filter=blob:none --sparse https://github.com/vernesong/OpenClash temp
          cd temp && git sparse-checkout set luci-app-openclash
          mv luci-app-openclash ../luci-app-openclash
          cd .. && rm -rf temp

          
  
          
      - name: Tambahkan file patch (MOD, CORE, APK)
        if: matrix.target == 'mod' || matrix.target == 'core' || matrix.target == 'apk'
        run: |
          set -e
          

          mkdir -p "$TARGET_DIR/package/luci-app-openclash/root/www/tinyfm"
          cp "$GITHUB_WORKSPACE/data/openclash/oceditor.php" "$TARGET_DIR/package/luci-app-openclash/root/www/tinyfm/"
          
          mkdir -p "$TARGET_DIR/package/luci-app-openclash/root/usr/share/openclash"
          cp "$GITHUB_WORKSPACE/data/openclash/ocmod.sh" "$TARGET_DIR/package/luci-app-openclash/root/usr/share/openclash/"
          chmod +x "$TARGET_DIR/package/luci-app-openclash/root/usr/share/openclash/ocmod.sh"
          
          # Hapus postinst-pkg jika ada, lalu tambahkan postinst baru di Makefile
          # Hapus postinst-pkg jika ada, lalu tambahkan postinst baru di Makefile
          cd "$TARGET_DIR/package/luci-app-openclash"
          if ! grep -q "ocmod.sh" Makefile; then
          sed -i '/define Package\/$(PKG_NAME)\/postinst/,/endef/{
            /exit 0/i [ -n "$$IPKG_INSTROOT" ] || {
            /exit 0/i \    chmod +x /usr/share/openclash/ocmod.sh
            /exit 0/i \    sh /usr/share/openclash/ocmod.sh
            /exit 0/i \    rm -f /usr/share/openclash/ocmod.sh
            /exit 0/i }
          }' Makefile
          fi

      - name: Download mihomo core (CORE, APK)
        if: matrix.target == 'core' || matrix.target == 'apk'
        run: |
          set -e
          
          cd "$TARGET_DIR/package/luci-app-openclash"
          mkdir -p root/etc/openclash/core
          TAG="Prerelease-Alpha"
          CORE_URL=$(curl -s https://api.github.com/repos/tes-rep/mihomo/releases/tags/$TAG | jq -r '.assets[] | select(.name | test("linux-arm64.*gz$")) | .browser_download_url')
          
          rm -f root/etc/openclash/core/clash_meta
          wget -O root/etc/openclash/core/clash_meta.gz "$CORE_URL"
          gunzip root/etc/openclash/core/clash_meta.gz
          chmod +x root/etc/openclash/core/clash_meta

      - name: Compile po2lmo
        run: |
          set -e
          cd "$TARGET_DIR/package/luci-app-openclash/tools/po2lmo"
          make && sudo make install

      - name: Compile luci-app-openclash
        run: |
          set -e
          FILE_SUFFIX=""
